{-# LANGUAGE OverloadedStrings #-}

module Spook.App.BootstrapCss where

import qualified Spook.App.Fluent as F

container, containerFluid, textCenter, row, jumbotron, formGroup, formControl, colFormLabel :: F.CssClass
colXs1, colXs2 , colXs3, colXs4, colXs5, colXs6, colXs7, colXs8, colXs9, colXs10, colXs11, colXs12 :: F.CssClass
colSm1 , colSm2 , colSm3 , colSm4 , colSm5 , colSm6 , colSm7 , colSm8 , colSm9 , colSm10, colSm11, colSm12 :: F.CssClass
colMd1 , colMd2 , colMd3 , colMd4 , colMd5 , colMd6 , colMd7 , colMd8 , colMd9 , colMd10, colMd11, colMd12 :: F.CssClass
colLg1 , colLg2 , colLg3 , colLg4 , colLg5 , colLg6 , colLg7 , colLg8 , colLg9 , colLg10, colLg11, colLg12 :: F.CssClass

colXsOffset1, colXsOffset2, colXsOffset3, colXsOffset4, colXsOffset5, colXsOffset6, colXsOffset7, colXsOffset8, colXsOffset9, colXsOffset10, colXsOffset11, colXsOffset12 :: F.CssClass
colSmOffset1, colSmOffset2, colSmOffset3, colSmOffset4, colSmOffset5, colSmOffset6, colSmOffset7, colSmOffset8, colSmOffset9, colSmOffset10, colSmOffset11, colSmOffset12 :: F.CssClass
colMdOffset1, colMdOffset2, colMdOffset3, colMdOffset4, colMdOffset5, colMdOffset6, colMdOffset7, colMdOffset8, colMdOffset9, colMdOffset10, colMdOffset11, colMdOffset12 :: F.CssClass
colLgOffset1, colLgOffset2, colLgOffset3, colLgOffset4, colLgOffset5, colLgOffset6, colLgOffset7, colLgOffset8, colLgOffset9, colLgOffset10, colLgOffset11, colLgOffset12 :: F.CssClass

container = "container"
containerFluid = "container-fluid"
textCenter = "text-center"
row = "row"
jumbotron = "jumbotron"
formGroup = "form-group"
formControl = "form-control"
colFormLabel = "col-form-label"
colXs1 = "col-xs-1"
colXs2 = "col-xs-2"
colXs3 = "col-xs-3"
colXs4 = "col-xs-4"
colXs5 = "col-xs-5"
colXs6 = "col-xs-6"
colXs7 = "col-xs-7"
colXs8 = "col-xs-8"
colXs9 = "col-xs-9"
colXs10 = "col-xs-10"
colXs11 = "col-xs-11"
colXs12 = "col-xs-12"
colSm1 = "col-sm-1"
colSm2 = "col-sm-2"
colSm3 = "col-sm-3"
colSm4 = "col-sm-4"
colSm5 = "col-sm-5"
colSm6 = "col-sm-6"
colSm7 = "col-sm-7"
colSm8 = "col-sm-8"
colSm9 = "col-sm-9"
colSm10 = "col-sm-10"
colSm11 = "col-sm-11"
colSm12 = "col-sm-12"
colMd1 = "col-md-1"
colMd2 = "col-md-2"
colMd3 = "col-md-3"
colMd4 = "col-md-4"
colMd5 = "col-md-5"
colMd6 = "col-md-6"
colMd7 = "col-md-7"
colMd8 = "col-md-8"
colMd9 = "col-md-9"
colMd10 = "col-md-10"
colMd11 = "col-md-11"
colMd12 = "col-md-12"
colLg1 = "col-lg-1"
colLg2 = "col-lg-2"
colLg3 = "col-lg-3"
colLg4 = "col-lg-4"
colLg5 = "col-lg-5"
colLg6 = "col-lg-6"
colLg7 = "col-lg-7"
colLg8 = "col-lg-8"
colLg9 = "col-lg-9"
colLg10 = "col-lg-10"
colLg11 = "col-lg-11"
colLg12 = "col-lg-12"

colXsOffset1 = "col-xs-offset-1"
colXsOffset2 = "col-xs-offset-2"
colXsOffset3 = "col-xs-offset-3"
colXsOffset4 = "col-xs-offset-4"
colXsOffset5 = "col-xs-offset-5"
colXsOffset6 = "col-xs-offset-6"
colXsOffset7 = "col-xs-offset-7"
colXsOffset8 = "col-xs-offset-8"
colXsOffset9 = "col-xs-offset-9"
colXsOffset10 = "col-xs-offset-10"
colXsOffset11 = "col-xs-offset-11"
colXsOffset12 = "col-xs-offset-12"
colSmOffset1 = "col-sm-offset-1"
colSmOffset2 = "col-sm-offset-2"
colSmOffset3 = "col-sm-offset-3"
colSmOffset4 = "col-sm-offset-4"
colSmOffset5 = "col-sm-offset-5"
colSmOffset6 = "col-sm-offset-6"
colSmOffset7 = "col-sm-offset-7"
colSmOffset8 = "col-sm-offset-8"
colSmOffset9 = "col-sm-offset-9"
colSmOffset10 = "col-sm-offset-10"
colSmOffset11 = "col-sm-offset-11"
colSmOffset12 = "col-sm-offset-12"
colMdOffset1 = "col-md-offset-1"
colMdOffset2 = "col-md-offset-2"
colMdOffset3 = "col-md-offset-3"
colMdOffset4 = "col-md-offset-4"
colMdOffset5 = "col-md-offset-5"
colMdOffset6 = "col-md-offset-6"
colMdOffset7 = "col-md-offset-7"
colMdOffset8 = "col-md-offset-8"
colMdOffset9 = "col-md-offset-9"
colMdOffset10 = "col-md-offset-10"
colMdOffset11 = "col-md-offset-11"
colMdOffset12 = "col-md-offset-12"
colLgOffset1 = "col-lg-offset-1"
colLgOffset2 = "col-lg-offset-2"
colLgOffset3 = "col-lg-offset-3"
colLgOffset4 = "col-lg-offset-4"
colLgOffset5 = "col-lg-offset-5"
colLgOffset6 = "col-lg-offset-6"
colLgOffset7 = "col-lg-offset-7"
colLgOffset8 = "col-lg-offset-8"
colLgOffset9 = "col-lg-offset-9"
colLgOffset10 = "col-lg-offset-10"
colLgOffset11 = "col-lg-offset-11"
colLgOffset12 = "col-lg-offset-12"
