{
 "title": "Spook App",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Request Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (handler, status_code)(rate(http_request_duration_microseconds_count{}[5m]))"
    }
   ]
  },
  {
   "title": "Request Error Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(http_request_duration_microseconds{handler=\"app\",status_code!=\"200\"})/count(http_request_duration_microseconds{handler=\"app\"})"
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(claim_token)" },
    { "expr": "sum(create_token)" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_microseconds{handler=\"app\"}) by (status_code, quantile)"
    }
   ]
  },
  {
   "title": "DB Query Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (query_name)(increase(db_latency_count{}[5m]))"
    }
   ]
  },
  {
   "title": "DB Query Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(db_latency_bucket[5m])) by (le)",
     "legendFormat": "{{le}} s"
    }
   ]
  }
 ]
}